services:
  pointcloud_server:
    container_name: pointcloud_server
    extends: 
      file: common.yaml
      service: .common_nvidia
    command: ros2 run pointcloud_server pointcloud_server_node
